/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2007-2013 Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-SNAPSHOT on 2010-03-15 23:22:35,
 Manually copied to svn because there are a BUNCH of problems with it generating converters.
 ==============================================================
 */

package org.sonatype.nexus.configuration.model.v1_4_1.upgrade;

//---------------------------------/
//- Imported classes and packages -/
//---------------------------------/

/**
 * Converts from version 1.4.0 (with version in package name) to
 * version 1.4.0 (without version in package name) of the model.
 *
 * @version $Revision$ $Date$
 */
@SuppressWarnings("all")
public interface VersionConverter
{

  //-----------/
  //- Methods -/
  //-----------/

  /**
   *
   *
   * @param cErrorReporting
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CErrorReporting convertCErrorReporting(
      org.sonatype.nexus.configuration.model.v1_4_0.CErrorReporting cErrorReporting);

  /**
   *
   *
   * @param cHttpProxySettings
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CHttpProxySettings convertCHttpProxySettings(
      org.sonatype.nexus.configuration.model.v1_4_0.CHttpProxySettings cHttpProxySettings);

  /**
   *
   *
   * @param cLocalStorage
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CLocalStorage convertCLocalStorage(
      org.sonatype.nexus.configuration.model.v1_4_0.CLocalStorage cLocalStorage);

  /**
   *
   *
   * @param cMirror
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CMirror convertCMirror(
      org.sonatype.nexus.configuration.model.v1_4_0.CMirror cMirror);

  /**
   *
   *
   * @param cPathMappingItem
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CPathMappingItem convertCPathMappingItem(
      org.sonatype.nexus.configuration.model.v1_4_0.CPathMappingItem cPathMappingItem);

  /**
   *
   *
   * @param cPlugin
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CPlugin convertCPlugin(
      org.sonatype.nexus.configuration.model.v1_4_0.CPlugin cPlugin);

  /**
   *
   *
   * @param cProps
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CProps convertCProps(
      org.sonatype.nexus.configuration.model.v1_4_0.CProps cProps);

  /**
   *
   *
   * @param cRemoteAuthentication
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRemoteAuthentication convertCRemoteAuthentication(
      org.sonatype.nexus.configuration.model.v1_4_0.CRemoteAuthentication cRemoteAuthentication);

  /**
   *
   *
   * @param cRemoteConnectionSettings
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRemoteConnectionSettings convertCRemoteConnectionSettings(
      org.sonatype.nexus.configuration.model.v1_4_0.CRemoteConnectionSettings cRemoteConnectionSettings);

  /**
   *
   *
   * @param cRemoteHttpProxySettings
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRemoteHttpProxySettings convertCRemoteHttpProxySettings(
      org.sonatype.nexus.configuration.model.v1_4_0.CRemoteHttpProxySettings cRemoteHttpProxySettings);

  /**
   *
   *
   * @param cRemoteNexusInstance
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRemoteNexusInstance convertCRemoteNexusInstance(
      org.sonatype.nexus.configuration.model.v1_4_0.CRemoteNexusInstance cRemoteNexusInstance);

  /**
   *
   *
   * @param cRemoteStorage
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRemoteStorage convertCRemoteStorage(
      org.sonatype.nexus.configuration.model.v1_4_0.CRemoteStorage cRemoteStorage);

  /**
   *
   *
   * @param cRepository
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRepository convertCRepository(
      org.sonatype.nexus.configuration.model.v1_4_0.CRepository cRepository);

  /**
   *
   *
   * @param cRepositoryGrouping
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRepositoryGrouping convertCRepositoryGrouping(
      org.sonatype.nexus.configuration.model.v1_4_0.CRepositoryGrouping cRepositoryGrouping);

  /**
   *
   *
   * @param cRepositoryTarget
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRepositoryTarget convertCRepositoryTarget(
      org.sonatype.nexus.configuration.model.v1_4_0.CRepositoryTarget cRepositoryTarget);

  /**
   *
   *
   * @param cRestApiSettings
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRestApiSettings convertCRestApiSettings(
      org.sonatype.nexus.configuration.model.v1_4_0.CRestApiSettings cRestApiSettings);

  /**
   *
   *
   * @param cRouting
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CRouting convertCRouting(
      org.sonatype.nexus.configuration.model.v1_4_0.CRouting cRouting);

  /**
   *
   *
   * @param cScheduleConfig
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CScheduleConfig convertCScheduleConfig(
      org.sonatype.nexus.configuration.model.v1_4_0.CScheduleConfig cScheduleConfig);

  /**
   *
   *
   * @param cScheduledTask
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CScheduledTask convertCScheduledTask(
      org.sonatype.nexus.configuration.model.v1_4_0.CScheduledTask cScheduledTask);

  /**
   *
   *
   * @param cSmtpConfiguration
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.CSmtpConfiguration convertCSmtpConfiguration(
      org.sonatype.nexus.configuration.model.v1_4_0.CSmtpConfiguration cSmtpConfiguration);

  /**
   *
   *
   * @param configuration
   */
  public org.sonatype.nexus.configuration.model.v1_4_1.Configuration convertConfiguration(
      org.sonatype.nexus.configuration.model.v1_4_0.Configuration configuration);
}
