package org.sonatype.security.ldap.dao.password;

import junit.framework.Assert;

import org.codehaus.plexus.PlexusTestCase;

public class PasswordEcoderTest
    extends PlexusTestCase
{
    private PasswordEncoderManager passwordEncoderManager;
    
    @Override
    public void setUp() throws Exception
    {
        super.setUp();
        this.passwordEncoderManager = this.lookup( PasswordEncoderManager.class );
    }
    
    public void testMD5()
    {
//        String cryptPassword = "{MD5}VtAV1lfgo6fnA60qDj64iA==";  generated by apacheds (for testing), uses hash
        String cryptPassword = "{MD5}56d015d657e0a3a7e703ad2a0e3eb888"; // just a simple md5 of the string
        String password = "md5123";
        
        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( cryptPassword, password, null ) );       
    }

    public void testClear()
    {
        String cryptPassword = "clear123";
        String password = "clear123";

        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( cryptPassword, password, null ) );
        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( "{CLEAR}"+cryptPassword, password, null ) );
    }
    
    public void testCrypt()
    {
//        String cryptPassword = "{CRYPT}h/Uf.HBpLVxmY"; generated by apacheds (for testing)
        String cryptPassword = "{CRYPT}$1$SpIxKuJe$KTEcMasljm9eC3CfgE72t/"; // generated by MD5Crypt.class
        String password = "crypt123";
        
        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( cryptPassword, password, null ) );       
    }
    
    public void testPlain()
    {
        String cryptPassword = "plain123";
        String password = "plain123";

        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( cryptPassword, password, null ) );
        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( "{PLAIN}"+cryptPassword, password, null ) );
    }
    
    public void testSha()
    {
        String cryptPassword = "{SHA}5Rs+hbtHUzvAhwkuaV5g7hW2KGc=";
        String password = "sha123";

        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( cryptPassword, password, null ) );       
    }
    
    public void testSsha()
    {
        String cryptPassword = "{SSHA}JoYvOj2uRZsp5hPMVgWmuwh0CnDwSgiQXMwPkg==";
        String password = "ssha123";

        Assert.assertTrue( this.passwordEncoderManager.isPasswordValid( cryptPassword, password, null ) );       
    }
    
    public void testQuick()
    {
        System.out.println( "MD5 'md5123': "+ new MD5CryptPasswordEncoder().encodePassword( "md5123", null ) );
    }
    
}
