//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 03:00:56 PM PDT 
//

package org.sonatype.nexus.logging.internal.ui

import groovy.transform.ToString
import org.apache.bval.constraints.NotEmpty

import javax.validation.constraints.NotNull

/**
 * Marker exchange object.
 *
 * @since 3.0
 */
@ToString(includePackage = false, includeNames = true)
class MarkerXO
{
  @NotNull
  @NotEmpty
  String message
}
