var processArguments=function(a){for(var b={},d=[],c,e=function(a,d){if(b.hasOwnProperty(a)){var e=b[a];e instanceof Array||(b[a]=[e]);b[a].push(d)}else b[a]=d;c=null},g=0;g<a.length;g++){var h=a[g],f=/--([\w_-]+)(?=\=(.*)|$)/.exec(h);f?(c&&e(c,!0),void 0!=f[2]?e(f[1],f[2]):c=f[1]):c?e(c,h):d.push(h)}c&&e(c,!0);return{options:b,argv:d}},constructURL=function(a,b){a.match(/^https?:\/\//)||(a="http://"+a);var d=!0,c;for(c in b)null!=b[c]&&(d=d?a.match(/\?/)?"&":"?":"&",a+=d+c+"="+encodeURIComponent(b[c]),
d=!1);return a},parseBrowser=function(a){var b="unknown",d="",c;if(c=/Firefox\/((?:\d+\.?)+)/.exec(a))b="Firefox",d=c[1];if(c=/Chrome\/((?:\d+\.?)+)/.exec(a))b="Chrome",d=c[1];if(c=/MSIE\s*((?:\d+\.?)+)/.exec(a))b="IE",d=c[1];if(c=/Apple.*Version\/((?:\d+\.?)+)\s*(?=Safari\/((?:\d+\.?)+))/.exec(a))b="Safari",d=c[1]+" ("+c[2]+")";return{name:b,version:d}},parseOS=function(a){return/Win/.test(a)?"Windows":/Mac/.test(a)?"MacOS":/Linux/.test(a)?"Linux":"unknown"},processCoverageOptions=function(a){var b=
a["coverage-report-format"]||"";b instanceof Array||(b=[b]);b.forEach(function(a,b,c){a=a.split(/\+|,/);1!=a.length&&(c[b]=a)});b=Array.prototype.concat.apply([],b).filter(function(a){return Boolean(a)});b.forEach(function(a){"html"!=a&&("raw"!=a&&"lcov"!=a)&&(print("Unrecognized coverage report format: "+a),quit(6))});var d=a["coverage-report-dir"]||convertPath("./coverage/"),d=d.replace(/\/?$/,""),c=0<b.length,e=a["coverage-unit"];e&&("file"!=e&&"extjs_class"!=e)&&(print("Unrecognized coverage unit: "+
e),quit(6));if(a=a["previous-coverage-report"]){var g;try{g=readFile(a)}catch(h){try{g=readFile(a.replace(/(\\|\/)?$/,"/")+"raw_coverage_data.json")}catch(f){print("Can't read the content of the previous raw coverage report: "+f),quit(6)}}try{if(g=JSON.parse(g),!g.coverageUnit||!g.rawReport)throw"";}catch(k){print("Previous raw coverage report is not a valid JSON or has wrong format"),quit(6)}a=g}return{enableCodeCoverage:c,coverageUnit:e,previousCoverageReport:a,coverageReportFormats:b,coverageReportDir:d}},
pollStep=function(a,b){var d=JSON.parse(a.executeScript("return Siesta.my.activeHarness.getPageState()")),c=d.lastActivity;b.lastActivityToken||(b.lastActivityToken=c,b.timeOfLastActivity=new Date);var e={exitCode:d.exitCode};c==b.lastActivityToken?18E4<new Date-b.timeOfLastActivity&&(e.exitCode=2):(b.lastActivityToken=c,b.timeOfLastActivity=new Date);d=d.log;"__NULL__"!=d&&(e.log=d);return e},pollPage=function(a,b,d,c){c=c||{};do{var e=pollStep(a,c);e.hasOwnProperty("log")&&a.print(e.log);null!=
e.exitCode?a.sleep(1E3,function(){d(e.exitCode)}):a.sleep(1E3,function(){b||pollPage(a,b,d,c)})}while(null==e.exitCode&&b)},runPage=function(a,b,d){var c=b.currentPage,e=b.enableCodeCoverage,g=b.shared;a.setWindowSize(b.viewportWidth,b.viewportHeight);a.debug("Opening harness page: "+b.url);a.open(b.url,function(){a.debug("Page opened successfully: "+b.url);var h=Number(a.executeScript("return Siesta.my.activeHarness.pageCount"));a.debug("Page count: "+h+", curent page: "+c);e&&g.contentManagerState&&
a.executeScript("__CONTENT_MANAGER_STATE__ = "+JSON.stringify(g.contentManagerState));pollPage(a,b.sync,function(f){a.debug("Page completed with exit code: "+f);2==f&&a.print("TIMEOUT: 3 minutes of inactivity");var k={exitCode:f,pageCount:h};0==h?(a.close(),d(k)):(f=c==h-1,k.pageReport=JSON.parse(a.executeScript("return Siesta.my.activeHarness.generateUnifiedPageReport()")),e&&(f||(g.contentManagerState=JSON.parse(a.executeScript("return Siesta.my.activeHarness.getContentManagerState(true)"))),g.coverageInfo=
JSON.parse(a.executeScript("return Siesta.my.activeHarness.getRawTotalCoverageInfo(true,"+JSON.stringify(g.coverageInfo)+")"))),f?d(k):(a.debug("Closing non-last page"),a.close(),a.sleep(b.pagePause||3E3,function(){d(k)})))})})},runBrowser=function(a,b,d){a.debug("Started browser session: "+a.browserName);var c=[],e=0,g=null,h=b.reportOptions,f=b.query,k=0,l=b.previousCoverageReport,p=l?{coverageInfo:l.rawReport,contentManagerState:l.contentManagerState}:{},m=function(){f.page=e;runPage(a,{url:constructURL(b.harnessURL,
f),viewportWidth:b.viewportWidth,viewportHeight:b.viewportHeight,currentPage:e,sync:b.sync,pagePause:b.pagePause,enableCodeCoverage:b.enableCodeCoverage,shared:p},function(f){e||(g=f.pageCount);k+=f.exitCode;if(g){var l=e==g-1;c.push(f.pageReport);if(l){f.summaryMessage?a.print(f.summaryMessage):(a.executeScript("__PAGE_REPORTS__ = "+JSON.stringify(c)),a.print(String(a.executeScript("return Siesta.my.activeHarness.getAutomatedSummaryMessage()"))));h&&(f.combinedReport?a.saveReport(f.combinedReport):
(h.pageReports=c,a.executeScript("__REPORT_OPTIONS__ = "+JSON.stringify(h)),a.saveReport(String(a.executeScript("return Siesta.my.activeHarness.generateReport()")))));if(b.enableCodeCoverage){var n=b.coverageReportDir;b.coverageReportFormats.forEach(function(b){switch(b){case "html":a.saveHtmlCoverageReport(n,f.htmlReport||JSON.parse(a.executeScript("return Siesta.my.activeHarness.generateCoverageHtmlReport(true)")));break;case "lcov":a.saveLcovCoverageReport(n,f.lcovReport||JSON.parse(a.executeScript("return Siesta.my.activeHarness.generateCoverageLcovReport(true)")));
break;case "raw":a.saveRawCoverageReport(n,f.rawReport||JSON.parse(a.executeScript("return Siesta.my.activeHarness.generateCoverageRawReport(true)")))}})}a.debug("Closing last page");a.close();d&&d(k)}else e++,b.sync||m()}else d&&d()})};m();if(b.sync)for(l=2;l<=g;l++)m()};
