/**
 * Copyright (c) 2008-2011 Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://www.sonatype.com/products/nexus/attributions.
 *
 * This program is free software: you can redistribute it and/or modify it only under the terms of the GNU Affero General
 * Public License Version 3 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License Version 3
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License Version 3 along with this program.  If not, see
 * http://www.gnu.org/licenses.
 *
 * Sonatype Nexus (TM) Open Source Version is available from Sonatype, Inc. Sonatype and Sonatype Nexus are trademarks of
 * Sonatype, Inc. Apache Maven is a trademark of the Apache Foundation. M2Eclipse is a trademark of the Eclipse Foundation.
 * All other trademarks are the property of their respective owners.
 */
/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3 on 2010-10-25 11:16:11,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.nexus.configuration.model.v1_4_5.upgrade;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/


/**
 * Converts from version 1.4.5 (with version in package name) to
 * version 1.4.5 (without version in package name) of the model.
 * 
 * @version $Revision: 7811 $ $Date: 2011-02-02 11:22:58 -0600 (Wed, 02 Feb 2011) $
 */
@SuppressWarnings( "all" )
public interface VersionConverter
{

    //-----------/
    // - Methods -/
    // -----------/

  /**
     * @param cErrorReporting
     */
    public org.sonatype.nexus.configuration.model.CErrorReporting convertCErrorReporting( org.sonatype.nexus.configuration.model.v1_4_4.CErrorReporting cErrorReporting );

    /**
     * @param cHttpProxySettings
     */
    public org.sonatype.nexus.configuration.model.CHttpProxySettings convertCHttpProxySettings( org.sonatype.nexus.configuration.model.v1_4_4.CHttpProxySettings cHttpProxySettings );

    /**
     * @param cLocalStorage
     */
    public org.sonatype.nexus.configuration.model.CLocalStorage convertCLocalStorage( org.sonatype.nexus.configuration.model.v1_4_4.CLocalStorage cLocalStorage );

    /**
     * @param cMirror
     */
    public org.sonatype.nexus.configuration.model.CMirror convertCMirror( org.sonatype.nexus.configuration.model.v1_4_4.CMirror cMirror );

    /**
     * @param cNotification
     */
    public org.sonatype.nexus.configuration.model.CNotification convertCNotification( org.sonatype.nexus.configuration.model.v1_4_4.CNotification cNotification );

    /**
     * @param cNotificationTarget
     */
    public org.sonatype.nexus.configuration.model.CNotificationTarget convertCNotificationTarget( org.sonatype.nexus.configuration.model.v1_4_4.CNotificationTarget cNotificationTarget );

    /**
     * @param cPathMappingItem
     */
    public org.sonatype.nexus.configuration.model.CPathMappingItem convertCPathMappingItem( org.sonatype.nexus.configuration.model.v1_4_4.CPathMappingItem cPathMappingItem );

    /**
     * @param cPlugin
     */
    public org.sonatype.nexus.configuration.model.CPlugin convertCPlugin( org.sonatype.nexus.configuration.model.v1_4_4.CPlugin cPlugin );

    /**
     * @param cProps
     */
    public org.sonatype.nexus.configuration.model.CProps convertCProps( org.sonatype.nexus.configuration.model.v1_4_4.CProps cProps );

    /**
     * @param cRemoteAuthentication
     */
    public org.sonatype.nexus.configuration.model.CRemoteAuthentication convertCRemoteAuthentication( org.sonatype.nexus.configuration.model.v1_4_4.CRemoteAuthentication cRemoteAuthentication );

    /**
     * @param cRemoteConnectionSettings
     */
    public org.sonatype.nexus.configuration.model.CRemoteConnectionSettings convertCRemoteConnectionSettings( org.sonatype.nexus.configuration.model.v1_4_4.CRemoteConnectionSettings cRemoteConnectionSettings );

    /**
     * @param cRemoteHttpProxySettings
     */
    public org.sonatype.nexus.configuration.model.CRemoteHttpProxySettings convertCRemoteHttpProxySettings( org.sonatype.nexus.configuration.model.v1_4_4.CRemoteHttpProxySettings cRemoteHttpProxySettings );

    /**
     * @param cRemoteNexusInstance
     */
    public org.sonatype.nexus.configuration.model.CRemoteNexusInstance convertCRemoteNexusInstance( org.sonatype.nexus.configuration.model.v1_4_4.CRemoteNexusInstance cRemoteNexusInstance );

    /**
     * @param cRemoteStorage
     */
    public org.sonatype.nexus.configuration.model.CRemoteStorage convertCRemoteStorage( org.sonatype.nexus.configuration.model.v1_4_4.CRemoteStorage cRemoteStorage );

    /**
     * @param cRepository
     */
    public org.sonatype.nexus.configuration.model.CRepository convertCRepository( org.sonatype.nexus.configuration.model.v1_4_4.CRepository cRepository );

    /**
     * @param cRepositoryGrouping
     */
    public org.sonatype.nexus.configuration.model.CRepositoryGrouping convertCRepositoryGrouping( org.sonatype.nexus.configuration.model.v1_4_4.CRepositoryGrouping cRepositoryGrouping );

    /**
     * @param cRepositoryTarget
     */
    public org.sonatype.nexus.configuration.model.CRepositoryTarget convertCRepositoryTarget( org.sonatype.nexus.configuration.model.v1_4_4.CRepositoryTarget cRepositoryTarget );

    /**
     * @param cRestApiSettings
     */
    public org.sonatype.nexus.configuration.model.CRestApiSettings convertCRestApiSettings( org.sonatype.nexus.configuration.model.v1_4_4.CRestApiSettings cRestApiSettings );

    /**
     * @param cRouting
     */
    public org.sonatype.nexus.configuration.model.CRouting convertCRouting( org.sonatype.nexus.configuration.model.v1_4_4.CRouting cRouting );

    /**
     * @param cScheduleConfig
     */
    public org.sonatype.nexus.configuration.model.CScheduleConfig convertCScheduleConfig( org.sonatype.nexus.configuration.model.v1_4_4.CScheduleConfig cScheduleConfig );

    /**
     * @param cScheduledTask
     */
    public org.sonatype.nexus.configuration.model.CScheduledTask convertCScheduledTask( org.sonatype.nexus.configuration.model.v1_4_4.CScheduledTask cScheduledTask );

    /**
     * @param cSmtpConfiguration
     */
    public org.sonatype.nexus.configuration.model.CSmtpConfiguration convertCSmtpConfiguration( org.sonatype.nexus.configuration.model.v1_4_4.CSmtpConfiguration cSmtpConfiguration );

    /**
     * @param configuration
     */
    public org.sonatype.nexus.configuration.model.Configuration convertConfiguration( org.sonatype.nexus.configuration.model.v1_4_4.Configuration configuration );
}
