//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 03:00:56 PM PDT 
//

package org.sonatype.nexus.logging.ui;

/**
 * Logger level.
 *
 * @since 3.0
 */
public enum LevelXO
{
  DEFAULT,
  TRACE,
  DEBUG,
  INFO,
  WARN,
  ERROR,
  OFF;
}
