/**
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2007-2012 Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.18 at 02:12:38 PM PDT 
//

package org.sonatype.nexus.plugin.settings.usertoken;

/**
 * Basic container for details usertoken/current REST end-point returns.
 *
 * @since 2.1
 */
public class UserTokenDTO
{
    protected String nameCode;

    protected String passCode;

    protected String created; // NOTE: Ignore date bits here for simplicity

    public String getNameCode() {
        return nameCode;
    }

    public void setNameCode(String value) {
        this.nameCode = value;
    }

    public String getPassCode() {
        return passCode;
    }

    public void setPassCode(String value) {
        this.passCode = value;
    }

    public String getCreated() {
        return created;
    }

    public void setCreated(String value) {
        this.created = value;
    }
}
