//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.18 at 02:12:38 PM PDT 
//

package org.sonatype.nexus.plugin.settings.usertoken;

/**
 * Basic container for details usertoken/current REST end-point returns.
 *
 * @since 2.1
 */
public class UserTokenDTO
{
    protected String nameCode;

    protected String passCode;

    protected String created; // NOTE: Ignore date bits here for simplicity

    public String getNameCode() {
        return nameCode;
    }

    public void setNameCode(String value) {
        this.nameCode = value;
    }

    public String getPassCode() {
        return passCode;
    }

    public void setPassCode(String value) {
        this.passCode = value;
    }

    public String getCreated() {
        return created;
    }

    public void setCreated(String value) {
        this.created = value;
    }
}
